services:
  - type: web
    name: api-docs
    env: static
    buildCommand: npx kohlrabi build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

